services:
  backend:
    container_name: app-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/game
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379
    ports:
      - 8080:8080

  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=game
    volumes:
      - ./dockerDB:/var/lib/postgresql/data

  cache:
    image: 'redis'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL